spring.application.name=lesson

server.port=3000

spring.datasource.url=jdbc:mysql://localhost:3306/video_lessons
spring.datasource.username=root
spring.datasource.password=admin123

spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/video-lesson